### ISSUE TITLE
Implement Sort

### ISSUE THREAD

**Issue by nevi-me** [nevi-me/rust-dataframe#16]
Add the ability to sort dataframe by one or multiple criteria. Before implementing this, look at what Arrow's doing, and whether it's possible to implement this functionality there.

**Comment by nevi-me** [comment]
The `take` kernel is nearly ready, this will make sorting possible. I can start prototyping how sorting will work

**Comment by xcaptain** [comment]
I like your `DataFrame` struct design, would be great to implement `Iterator` for it which can make `sort`, `filter`, `map` easier

**Comment by nevi-me** [comment]
Hey @xcaptain, thanks. It's tempting to use iterators as Rust would provide a lot of operators for them, however I'm taking a deliberate design of operating on data in a columnar format. I'm going to rely on Apache Arrow for a lot of the computation stuff. It already have `filter`, `limit` and a few other basic building blocks.

For example, the `take` kernel is available on Arrow (https://docs.rs/arrow/0.15.1/arrow/compute/kernels/take/fn.take.html). It is one part of sorting, where most of the work that remains is in producing an index array to sort with.

**Comment by xcaptain** [comment]
I found https://github.com/dotnet/corefxlab/tree/master/src/Microsoft.Data.Analysis interesting, this project tries to implement a dataframe for C#, it uses Arrow but only provides a bridge a convert between Arrow.

**Comment by nevi-me** [comment]
I'll be able to implement `sort` after completing it upstream in Arrow
