### ISSUE TITLE
Add Arrow IPC datasource

### ISSUE THREAD

**Issue by nevi-me** [nevi-me/rust-dataframe#26]
Arrow 0.16.0 will include read and write support for the Arrow IPC formats. Adding support for this would allow round-trip IO

**Comment by andygrove** [comment]
I'm watching this with interest ... have you also seen native_spark [1] and ballista [2]? It seems there are a few efforts here that could potentially converge.

[1] https://github.com/rajasekarv/native_spark
[2] https://github.com/andygrove/ballista

**Comment by nevi-me** [comment]
I had seen native_spark on Reddit a few weeks ago, but haven't looked at its source code. I haven't tried ballista out yet, I can never get kubernetes working on my laptop :(

I suppose I'm targeting the typical non-distributed analytics users like pandas users with this dataframe, but I want to see if anything useful/performant could come out of it.
