### ISSUE TITLE
partitioned parquet dataset as data source

### ISSUE THREAD

**Issue by houqp** [nevi-me/rust-dataframe#37]
I am interested in working on adding support for loading a partitioned parquet dataset (multiple files) as datasource in a read transformation.

What do you think is the best way to implement this? Here are couple options that come to my mind:

* add a new variant `DataSrouceType::ParquetDataset`
* extend `DataSrouceType::Parquet` to also take a list of file paths
* introduce to higher level abstraction that represents a sequence of data sources so other formats like CSV can reuse this feature as well

**Comment by nevi-me** [comment]
Hi @houqp, option 3 sounds very interesting. Would partitioned writes also make sense? They often make more sense in Spark, especially as the user could repartition the dataframe to write a single partition, I don't know how useful they'd be in this dataframe.

**Comment by houqp** [comment]
yeah, I can see partition write being useful as well, since how data is being partitioned could drastically impact subsequent read performance, even within a single machine.

**Comment by houqp** [comment]
@nevi-me I am having a second thought on this topic, it might be better to go with option 4, which is to implement the same behaviour that spark has: if user wants to load a single file, then use `DataSourceType::Parquet("foo/bar.parquet")`. For loading a partitioned dataset, they can just change it to `DataSourceType::Parquet("foo/*")`.

**Comment by nevi-me** [comment]
As long as it doesn't add a lot of complexity, it's fine. You could also allow foregoing the asterisk by checking if the path is a file or folder, and assuming that the files inside are to all be read.

**Comment by nevi-me** [comment]
fixed by #40
