### ISSUE TITLE
Implement sort for floats

### ISSUE THREAD

**Issue by nevi-me** [nevi-me/rust-dataframe#48]

**Comment by fgadaleta** [comment]
To clarify what is needed here, sorting would be applied to Column and the sorted indexes would be sorting the other columns of the dataframe. Is this what you intend to implement? 

Is this the same expected to happen in the other sorting issues?

**Comment by nevi-me** [comment]
Hey @fgadaleta, we rely on Apache Arrow for sorting, and at the time that I opened this PR, sorting by floats wasn't yet implemented. This issue is likely no longer relevant as Arrow now supports sorting by floats. The one on sorting lists is still relevant, as Arrow doesn't yet support sorting on lists
