### ISSUE TITLE
Implement sort for string arrays

### ISSUE THREAD

**Issue by nevi-me** [nevi-me/rust-dataframe#49]

**Comment by fgadaleta** [comment]
What do you mean with sorting for binary? 
While a string array might be alphabetically sorted, how would a binary object be?

**Comment by nevi-me** [comment]
You're right, doesn't make sense to sort a binary, but maybe things like IP addresses could still be sorted if they're represented as a fixed size binary

**Comment by nevi-me** [comment]
This is implemented in Arrow
