### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by petri-dev** [nevi-me/rust-dataframe#57]
Hi - I appreciate the good work you guys are doing here and I'd like to contribute to this project. Is there a way to get in contact? My e-mail address is chrisharriscjh@gmail.com.

**Comment by nevi-me** [comment]
Hi @petri-dev, thanks for reaching out. I've been meaning to write another update with some direction on what I'd like to focus on, but haven't had the time to yet.

I'm spending more time upstream on Apache Arrow as there's some core functionality there that I need for this project.

I'm also trying to write SQL - Arrow conversions, much of that work is in progress and is on my local branches. There's already a Postgresql reader and writer, if you're comfortable with profiling allocations, that would be something great to look into. I'll open issues for some of what I'm exploring.

**Comment by petri-dev** [comment]
Hi Wakahisa, thanks for getting in contact. In terms of my own background,
I have a reasonable amount of data science coding experience in Python,
using the numpy/pandas ecosystem, and I know those packages well. I do my
non-data-science programming in Scala. I have only been using Rust for the
past few months, and I would see contributing to this project as a way to
get to know it better. I've also been interested in the developments with
Apache Arrow but have been keeping an eye on it rather than actually using
it. I have quite limited database experience (I have used Scala's SQL ORM a
couple of times with a MySQL database).

I (unfortunately) have a full-time job, but I usually find 6 or so hours
per week for side projects. If you think that I could usefully contribute
based on this info, I'd be happy to do so. You mention that you're working
on 'another' update on what the direction of the project should be - if you
could point me towards the previous update then it might be a useful
introduction.

**Comment by nevi-me** [comment]
i unfortunately never got the time to do this :(
